version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-egress-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rrxhgkf4c247"
s3_prefix = "test-egress-app"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
