AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: SAM app that automatically downloads and processes the outputs of completed jobs from the Voxel51 Platform.

Parameters:
  Voxel51ApiToken:
    Type: String
    Default: ''
  OutputBucketName:
    Type: String
    Default: ''

Resources:
  EgressFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.6
      Timeout: 180
      Environment:
        Variables:
          SECRET_ARN:
            Ref: ApiToken
          BUCKET_NAME:
            Ref: OutputBucketName
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 's3:PutObject'
                - 's3:PutObjectACL'
              Resource: !Sub 'arn:aws:s3:::v51-output-${AWS::AccountId}/*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'secretsmanager:GetSecretValue'
              Resource:
                Ref: ApiToken
      Events:
        JobCompleteRoute:
          Type: Api
          Properties:
            Path: /job-complete
            Method: post
  OutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref OutputBucketName
  ApiToken:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      SecretString:
        Ref: Voxel51ApiToken

Outputs:
  EgressAPI:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/job-complete"
  EgressFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt EgressFunction.Arn
  EgressFunctionIamRole:
    Description: "Implicit IAM Role created for Lambda Function"
    Value: !GetAtt EgressFunctionRole.Arn
